version: "3.9"

services:
  db:
    image: postgres:16
    container_name: actas_db
    environment:
      POSTGRES_DB: actas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Guayaquil
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d actas_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    container_name: actas_web
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: actas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgresql://postgres:postgres@db:5432/actas_db
      SECRET_KEY: change-me
      TZ: America/Guayaquil
    ports:
      - "8080:8000"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.11
    container_name: actas_pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin:
